//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CER_POSTGRADO
    {
        public int npostgrado_id { get; set; }
        public Nullable<System.DateTime> dpostgrado_fecha { get; set; }
        public string vpostgrado_nombre { get; set; }
        public Nullable<int> ninstitucionedu_id { get; set; }
        public Nullable<int> cmedico_id { get; set; }
        public string cpostgrado_tipo { get; set; }
    
        public virtual CMP_INSTITUCIONEDU CMP_INSTITUCIONEDU { get; set; }
        public virtual CMP_MEDICO CMP_MEDICO { get; set; }
    }
}
