//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CER_PASANTIA
    {
        public int npasantia_id { get; set; }
        public string vpasantia_dsc { get; set; }
        public Nullable<System.DateTime> dpasantia_inicio { get; set; }
        public Nullable<System.DateTime> dpasantia_fin { get; set; }
        public Nullable<int> npresatadora_id { get; set; }
        public Nullable<int> cmedico_id { get; set; }
    
        public virtual CMP_MEDICO CMP_MEDICO { get; set; }
        public virtual CMP_PRESTADORA CMP_PRESTADORA { get; set; }
    }
}
