//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMP_MEDICOESP
    {
        public int CMEDICOESP_ID { get; set; }
        public string VMEDICOESP_COD { get; set; }
        public Nullable<int> CMEDICO_ID { get; set; }
        public Nullable<int> NESPECIALIDAD_ID { get; set; }
        public Nullable<System.DateTime> DMEDICOESP_EMISION { get; set; }
        public Nullable<System.DateTime> DMEDICOESP_CADUCIDAD { get; set; }
        public Nullable<System.DateTime> DMEDICOESP_RESOLUCION { get; set; }
    
        public virtual CMP_ESPECIALIDAD CMP_ESPECIALIDAD { get; set; }
        public virtual CMP_MEDICO CMP_MEDICO { get; set; }
    }
}
