//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMP_CREGIONAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMP_CREGIONAL()
        {
            this.CMP_MEDICO = new HashSet<CMP_MEDICO>();
        }
    
        public int ncregional_id { get; set; }
        public string vcregional_cod { get; set; }
        public string vcregional_nombre { get; set; }
        public string vcregional_abr { get; set; }
        public string vcregional_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMP_MEDICO> CMP_MEDICO { get; set; }
    }
}
