//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMP_ESPECIALIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMP_ESPECIALIDAD()
        {
            this.CMP_MEDICOESP = new HashSet<CMP_MEDICOESP>();
        }
    
        public int nespecialidad_id { get; set; }
        public string cespecialidad_estado { get; set; }
        public string cespecialidad_nombre { get; set; }
        public string vespecialidad_cod { get; set; }
        public string vespecialidad_tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMP_MEDICOESP> CMP_MEDICOESP { get; set; }
    }
}
