//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ColegioMPEntities : DbContext
    {
        public ColegioMPEntities()
            : base("name=ColegioMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CER_PASANTIA> CER_PASANTIA { get; set; }
        public virtual DbSet<CER_POSTGRADO> CER_POSTGRADO { get; set; }
        public virtual DbSet<CMP_CREGIONAL> CMP_CREGIONAL { get; set; }
        public virtual DbSet<CMP_ESPECIALIDAD> CMP_ESPECIALIDAD { get; set; }
        public virtual DbSet<CMP_INSTITUCIONEDU> CMP_INSTITUCIONEDU { get; set; }
        public virtual DbSet<CMP_MEDICO> CMP_MEDICO { get; set; }
        public virtual DbSet<CMP_MEDICOESP> CMP_MEDICOESP { get; set; }
        public virtual DbSet<CMP_PRESTADORA> CMP_PRESTADORA { get; set; }
        public virtual DbSet<CMP_UBIGEO> CMP_UBIGEO { get; set; }
    
        public virtual int usp_CER_PASANTIADelete(Nullable<int> npasantia_id)
        {
            var npasantia_idParameter = npasantia_id.HasValue ?
                new ObjectParameter("npasantia_id", npasantia_id) :
                new ObjectParameter("npasantia_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CER_PASANTIADelete", npasantia_idParameter);
        }
    
        public virtual ObjectResult<usp_CER_PASANTIAInsert_Result> usp_CER_PASANTIAInsert(string vpasantia_dsc, Nullable<System.DateTime> dpasantia_inicio, Nullable<System.DateTime> dpasantia_fin, Nullable<int> npresatadora_id, Nullable<int> cmedico_id)
        {
            var vpasantia_dscParameter = vpasantia_dsc != null ?
                new ObjectParameter("vpasantia_dsc", vpasantia_dsc) :
                new ObjectParameter("vpasantia_dsc", typeof(string));
    
            var dpasantia_inicioParameter = dpasantia_inicio.HasValue ?
                new ObjectParameter("dpasantia_inicio", dpasantia_inicio) :
                new ObjectParameter("dpasantia_inicio", typeof(System.DateTime));
    
            var dpasantia_finParameter = dpasantia_fin.HasValue ?
                new ObjectParameter("dpasantia_fin", dpasantia_fin) :
                new ObjectParameter("dpasantia_fin", typeof(System.DateTime));
    
            var npresatadora_idParameter = npresatadora_id.HasValue ?
                new ObjectParameter("npresatadora_id", npresatadora_id) :
                new ObjectParameter("npresatadora_id", typeof(int));
    
            var cmedico_idParameter = cmedico_id.HasValue ?
                new ObjectParameter("cmedico_id", cmedico_id) :
                new ObjectParameter("cmedico_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CER_PASANTIAInsert_Result>("usp_CER_PASANTIAInsert", vpasantia_dscParameter, dpasantia_inicioParameter, dpasantia_finParameter, npresatadora_idParameter, cmedico_idParameter);
        }
    
        public virtual ObjectResult<usp_CER_PASANTIASelect_Result> usp_CER_PASANTIASelect(Nullable<int> npasantia_id)
        {
            var npasantia_idParameter = npasantia_id.HasValue ?
                new ObjectParameter("npasantia_id", npasantia_id) :
                new ObjectParameter("npasantia_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CER_PASANTIASelect_Result>("usp_CER_PASANTIASelect", npasantia_idParameter);
        }
    
        public virtual ObjectResult<usp_CER_PASANTIAUpdate_Result> usp_CER_PASANTIAUpdate(Nullable<int> npasantia_id, string vpasantia_dsc, Nullable<System.DateTime> dpasantia_inicio, Nullable<System.DateTime> dpasantia_fin, Nullable<int> npresatadora_id, Nullable<int> cmedico_id)
        {
            var npasantia_idParameter = npasantia_id.HasValue ?
                new ObjectParameter("npasantia_id", npasantia_id) :
                new ObjectParameter("npasantia_id", typeof(int));
    
            var vpasantia_dscParameter = vpasantia_dsc != null ?
                new ObjectParameter("vpasantia_dsc", vpasantia_dsc) :
                new ObjectParameter("vpasantia_dsc", typeof(string));
    
            var dpasantia_inicioParameter = dpasantia_inicio.HasValue ?
                new ObjectParameter("dpasantia_inicio", dpasantia_inicio) :
                new ObjectParameter("dpasantia_inicio", typeof(System.DateTime));
    
            var dpasantia_finParameter = dpasantia_fin.HasValue ?
                new ObjectParameter("dpasantia_fin", dpasantia_fin) :
                new ObjectParameter("dpasantia_fin", typeof(System.DateTime));
    
            var npresatadora_idParameter = npresatadora_id.HasValue ?
                new ObjectParameter("npresatadora_id", npresatadora_id) :
                new ObjectParameter("npresatadora_id", typeof(int));
    
            var cmedico_idParameter = cmedico_id.HasValue ?
                new ObjectParameter("cmedico_id", cmedico_id) :
                new ObjectParameter("cmedico_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CER_PASANTIAUpdate_Result>("usp_CER_PASANTIAUpdate", npasantia_idParameter, vpasantia_dscParameter, dpasantia_inicioParameter, dpasantia_finParameter, npresatadora_idParameter, cmedico_idParameter);
        }
    
        public virtual int usp_CER_POSTGRADODelete(Nullable<int> npostgrado_id)
        {
            var npostgrado_idParameter = npostgrado_id.HasValue ?
                new ObjectParameter("npostgrado_id", npostgrado_id) :
                new ObjectParameter("npostgrado_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CER_POSTGRADODelete", npostgrado_idParameter);
        }
    
        public virtual ObjectResult<usp_CER_POSTGRADOInsert_Result> usp_CER_POSTGRADOInsert(Nullable<System.DateTime> dpostgrado_fecha, string vpostgrado_nombre, Nullable<int> ninstitucionedu_id, Nullable<int> cmedico_id, string cpostgrado_tipo)
        {
            var dpostgrado_fechaParameter = dpostgrado_fecha.HasValue ?
                new ObjectParameter("dpostgrado_fecha", dpostgrado_fecha) :
                new ObjectParameter("dpostgrado_fecha", typeof(System.DateTime));
    
            var vpostgrado_nombreParameter = vpostgrado_nombre != null ?
                new ObjectParameter("vpostgrado_nombre", vpostgrado_nombre) :
                new ObjectParameter("vpostgrado_nombre", typeof(string));
    
            var ninstitucionedu_idParameter = ninstitucionedu_id.HasValue ?
                new ObjectParameter("ninstitucionedu_id", ninstitucionedu_id) :
                new ObjectParameter("ninstitucionedu_id", typeof(int));
    
            var cmedico_idParameter = cmedico_id.HasValue ?
                new ObjectParameter("cmedico_id", cmedico_id) :
                new ObjectParameter("cmedico_id", typeof(int));
    
            var cpostgrado_tipoParameter = cpostgrado_tipo != null ?
                new ObjectParameter("cpostgrado_tipo", cpostgrado_tipo) :
                new ObjectParameter("cpostgrado_tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CER_POSTGRADOInsert_Result>("usp_CER_POSTGRADOInsert", dpostgrado_fechaParameter, vpostgrado_nombreParameter, ninstitucionedu_idParameter, cmedico_idParameter, cpostgrado_tipoParameter);
        }
    
        public virtual ObjectResult<usp_CER_POSTGRADOSelect_Result> usp_CER_POSTGRADOSelect(Nullable<int> npostgrado_id)
        {
            var npostgrado_idParameter = npostgrado_id.HasValue ?
                new ObjectParameter("npostgrado_id", npostgrado_id) :
                new ObjectParameter("npostgrado_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CER_POSTGRADOSelect_Result>("usp_CER_POSTGRADOSelect", npostgrado_idParameter);
        }
    
        public virtual ObjectResult<usp_CER_POSTGRADOUpdate_Result> usp_CER_POSTGRADOUpdate(Nullable<int> npostgrado_id, Nullable<System.DateTime> dpostgrado_fecha, string vpostgrado_nombre, Nullable<int> ninstitucionedu_id, Nullable<int> cmedico_id, string cpostgrado_tipo)
        {
            var npostgrado_idParameter = npostgrado_id.HasValue ?
                new ObjectParameter("npostgrado_id", npostgrado_id) :
                new ObjectParameter("npostgrado_id", typeof(int));
    
            var dpostgrado_fechaParameter = dpostgrado_fecha.HasValue ?
                new ObjectParameter("dpostgrado_fecha", dpostgrado_fecha) :
                new ObjectParameter("dpostgrado_fecha", typeof(System.DateTime));
    
            var vpostgrado_nombreParameter = vpostgrado_nombre != null ?
                new ObjectParameter("vpostgrado_nombre", vpostgrado_nombre) :
                new ObjectParameter("vpostgrado_nombre", typeof(string));
    
            var ninstitucionedu_idParameter = ninstitucionedu_id.HasValue ?
                new ObjectParameter("ninstitucionedu_id", ninstitucionedu_id) :
                new ObjectParameter("ninstitucionedu_id", typeof(int));
    
            var cmedico_idParameter = cmedico_id.HasValue ?
                new ObjectParameter("cmedico_id", cmedico_id) :
                new ObjectParameter("cmedico_id", typeof(int));
    
            var cpostgrado_tipoParameter = cpostgrado_tipo != null ?
                new ObjectParameter("cpostgrado_tipo", cpostgrado_tipo) :
                new ObjectParameter("cpostgrado_tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CER_POSTGRADOUpdate_Result>("usp_CER_POSTGRADOUpdate", npostgrado_idParameter, dpostgrado_fechaParameter, vpostgrado_nombreParameter, ninstitucionedu_idParameter, cmedico_idParameter, cpostgrado_tipoParameter);
        }
    
        public virtual int usp_CMP_CREGIONALDelete(Nullable<int> ncregional_id)
        {
            var ncregional_idParameter = ncregional_id.HasValue ?
                new ObjectParameter("ncregional_id", ncregional_id) :
                new ObjectParameter("ncregional_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CMP_CREGIONALDelete", ncregional_idParameter);
        }
    
        public virtual ObjectResult<usp_CMP_CREGIONALInsert_Result> usp_CMP_CREGIONALInsert(string vcregional_cod, string vcregional_nombre, string vcregional_abr, string vcregional_estado)
        {
            var vcregional_codParameter = vcregional_cod != null ?
                new ObjectParameter("vcregional_cod", vcregional_cod) :
                new ObjectParameter("vcregional_cod", typeof(string));
    
            var vcregional_nombreParameter = vcregional_nombre != null ?
                new ObjectParameter("vcregional_nombre", vcregional_nombre) :
                new ObjectParameter("vcregional_nombre", typeof(string));
    
            var vcregional_abrParameter = vcregional_abr != null ?
                new ObjectParameter("vcregional_abr", vcregional_abr) :
                new ObjectParameter("vcregional_abr", typeof(string));
    
            var vcregional_estadoParameter = vcregional_estado != null ?
                new ObjectParameter("vcregional_estado", vcregional_estado) :
                new ObjectParameter("vcregional_estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_CREGIONALInsert_Result>("usp_CMP_CREGIONALInsert", vcregional_codParameter, vcregional_nombreParameter, vcregional_abrParameter, vcregional_estadoParameter);
        }
    
        public virtual ObjectResult<usp_CMP_CREGIONALSelect_Result> usp_CMP_CREGIONALSelect(Nullable<int> ncregional_id)
        {
            var ncregional_idParameter = ncregional_id.HasValue ?
                new ObjectParameter("ncregional_id", ncregional_id) :
                new ObjectParameter("ncregional_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_CREGIONALSelect_Result>("usp_CMP_CREGIONALSelect", ncregional_idParameter);
        }
    
        public virtual ObjectResult<usp_CMP_CREGIONALUpdate_Result> usp_CMP_CREGIONALUpdate(Nullable<int> ncregional_id, string vcregional_cod, string vcregional_nombre, string vcregional_abr, string vcregional_estado)
        {
            var ncregional_idParameter = ncregional_id.HasValue ?
                new ObjectParameter("ncregional_id", ncregional_id) :
                new ObjectParameter("ncregional_id", typeof(int));
    
            var vcregional_codParameter = vcregional_cod != null ?
                new ObjectParameter("vcregional_cod", vcregional_cod) :
                new ObjectParameter("vcregional_cod", typeof(string));
    
            var vcregional_nombreParameter = vcregional_nombre != null ?
                new ObjectParameter("vcregional_nombre", vcregional_nombre) :
                new ObjectParameter("vcregional_nombre", typeof(string));
    
            var vcregional_abrParameter = vcregional_abr != null ?
                new ObjectParameter("vcregional_abr", vcregional_abr) :
                new ObjectParameter("vcregional_abr", typeof(string));
    
            var vcregional_estadoParameter = vcregional_estado != null ?
                new ObjectParameter("vcregional_estado", vcregional_estado) :
                new ObjectParameter("vcregional_estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_CREGIONALUpdate_Result>("usp_CMP_CREGIONALUpdate", ncregional_idParameter, vcregional_codParameter, vcregional_nombreParameter, vcregional_abrParameter, vcregional_estadoParameter);
        }
    
        public virtual int usp_CMP_ESPECIALIDADDelete(Nullable<int> nespecialidad_id)
        {
            var nespecialidad_idParameter = nespecialidad_id.HasValue ?
                new ObjectParameter("nespecialidad_id", nespecialidad_id) :
                new ObjectParameter("nespecialidad_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CMP_ESPECIALIDADDelete", nespecialidad_idParameter);
        }
    
        public virtual ObjectResult<usp_CMP_ESPECIALIDADInsert_Result> usp_CMP_ESPECIALIDADInsert(string cespecialidad_estado, string cespecialidad_nombre, string vespecialidad_cod, string vespecialidad_tipo)
        {
            var cespecialidad_estadoParameter = cespecialidad_estado != null ?
                new ObjectParameter("cespecialidad_estado", cespecialidad_estado) :
                new ObjectParameter("cespecialidad_estado", typeof(string));
    
            var cespecialidad_nombreParameter = cespecialidad_nombre != null ?
                new ObjectParameter("cespecialidad_nombre", cespecialidad_nombre) :
                new ObjectParameter("cespecialidad_nombre", typeof(string));
    
            var vespecialidad_codParameter = vespecialidad_cod != null ?
                new ObjectParameter("vespecialidad_cod", vespecialidad_cod) :
                new ObjectParameter("vespecialidad_cod", typeof(string));
    
            var vespecialidad_tipoParameter = vespecialidad_tipo != null ?
                new ObjectParameter("vespecialidad_tipo", vespecialidad_tipo) :
                new ObjectParameter("vespecialidad_tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_ESPECIALIDADInsert_Result>("usp_CMP_ESPECIALIDADInsert", cespecialidad_estadoParameter, cespecialidad_nombreParameter, vespecialidad_codParameter, vespecialidad_tipoParameter);
        }
    
        public virtual ObjectResult<usp_CMP_ESPECIALIDADSelect_Result> usp_CMP_ESPECIALIDADSelect(Nullable<int> nespecialidad_id)
        {
            var nespecialidad_idParameter = nespecialidad_id.HasValue ?
                new ObjectParameter("nespecialidad_id", nespecialidad_id) :
                new ObjectParameter("nespecialidad_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_ESPECIALIDADSelect_Result>("usp_CMP_ESPECIALIDADSelect", nespecialidad_idParameter);
        }
    
        public virtual ObjectResult<usp_CMP_ESPECIALIDADUpdate_Result> usp_CMP_ESPECIALIDADUpdate(Nullable<int> nespecialidad_id, string cespecialidad_estado, string cespecialidad_nombre, string vespecialidad_cod, string vespecialidad_tipo)
        {
            var nespecialidad_idParameter = nespecialidad_id.HasValue ?
                new ObjectParameter("nespecialidad_id", nespecialidad_id) :
                new ObjectParameter("nespecialidad_id", typeof(int));
    
            var cespecialidad_estadoParameter = cespecialidad_estado != null ?
                new ObjectParameter("cespecialidad_estado", cespecialidad_estado) :
                new ObjectParameter("cespecialidad_estado", typeof(string));
    
            var cespecialidad_nombreParameter = cespecialidad_nombre != null ?
                new ObjectParameter("cespecialidad_nombre", cespecialidad_nombre) :
                new ObjectParameter("cespecialidad_nombre", typeof(string));
    
            var vespecialidad_codParameter = vespecialidad_cod != null ?
                new ObjectParameter("vespecialidad_cod", vespecialidad_cod) :
                new ObjectParameter("vespecialidad_cod", typeof(string));
    
            var vespecialidad_tipoParameter = vespecialidad_tipo != null ?
                new ObjectParameter("vespecialidad_tipo", vespecialidad_tipo) :
                new ObjectParameter("vespecialidad_tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_ESPECIALIDADUpdate_Result>("usp_CMP_ESPECIALIDADUpdate", nespecialidad_idParameter, cespecialidad_estadoParameter, cespecialidad_nombreParameter, vespecialidad_codParameter, vespecialidad_tipoParameter);
        }
    
        public virtual int usp_CMP_INSTITUCIONEDUDelete(Nullable<int> ninstitucionedu_id)
        {
            var ninstitucionedu_idParameter = ninstitucionedu_id.HasValue ?
                new ObjectParameter("ninstitucionedu_id", ninstitucionedu_id) :
                new ObjectParameter("ninstitucionedu_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CMP_INSTITUCIONEDUDelete", ninstitucionedu_idParameter);
        }
    
        public virtual ObjectResult<usp_CMP_INSTITUCIONEDUInsert_Result> usp_CMP_INSTITUCIONEDUInsert(string cinstitucionedu_nombre, string cinstitucionedu_tipo, string cinstitucionedu_estado)
        {
            var cinstitucionedu_nombreParameter = cinstitucionedu_nombre != null ?
                new ObjectParameter("cinstitucionedu_nombre", cinstitucionedu_nombre) :
                new ObjectParameter("cinstitucionedu_nombre", typeof(string));
    
            var cinstitucionedu_tipoParameter = cinstitucionedu_tipo != null ?
                new ObjectParameter("cinstitucionedu_tipo", cinstitucionedu_tipo) :
                new ObjectParameter("cinstitucionedu_tipo", typeof(string));
    
            var cinstitucionedu_estadoParameter = cinstitucionedu_estado != null ?
                new ObjectParameter("cinstitucionedu_estado", cinstitucionedu_estado) :
                new ObjectParameter("cinstitucionedu_estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_INSTITUCIONEDUInsert_Result>("usp_CMP_INSTITUCIONEDUInsert", cinstitucionedu_nombreParameter, cinstitucionedu_tipoParameter, cinstitucionedu_estadoParameter);
        }
    
        public virtual ObjectResult<usp_CMP_INSTITUCIONEDUSelect_Result> usp_CMP_INSTITUCIONEDUSelect(Nullable<int> ninstitucionedu_id)
        {
            var ninstitucionedu_idParameter = ninstitucionedu_id.HasValue ?
                new ObjectParameter("ninstitucionedu_id", ninstitucionedu_id) :
                new ObjectParameter("ninstitucionedu_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_INSTITUCIONEDUSelect_Result>("usp_CMP_INSTITUCIONEDUSelect", ninstitucionedu_idParameter);
        }
    
        public virtual ObjectResult<usp_CMP_INSTITUCIONEDUUpdate_Result> usp_CMP_INSTITUCIONEDUUpdate(Nullable<int> ninstitucionedu_id, string cinstitucionedu_nombre, string cinstitucionedu_tipo, string cinstitucionedu_estado)
        {
            var ninstitucionedu_idParameter = ninstitucionedu_id.HasValue ?
                new ObjectParameter("ninstitucionedu_id", ninstitucionedu_id) :
                new ObjectParameter("ninstitucionedu_id", typeof(int));
    
            var cinstitucionedu_nombreParameter = cinstitucionedu_nombre != null ?
                new ObjectParameter("cinstitucionedu_nombre", cinstitucionedu_nombre) :
                new ObjectParameter("cinstitucionedu_nombre", typeof(string));
    
            var cinstitucionedu_tipoParameter = cinstitucionedu_tipo != null ?
                new ObjectParameter("cinstitucionedu_tipo", cinstitucionedu_tipo) :
                new ObjectParameter("cinstitucionedu_tipo", typeof(string));
    
            var cinstitucionedu_estadoParameter = cinstitucionedu_estado != null ?
                new ObjectParameter("cinstitucionedu_estado", cinstitucionedu_estado) :
                new ObjectParameter("cinstitucionedu_estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_INSTITUCIONEDUUpdate_Result>("usp_CMP_INSTITUCIONEDUUpdate", ninstitucionedu_idParameter, cinstitucionedu_nombreParameter, cinstitucionedu_tipoParameter, cinstitucionedu_estadoParameter);
        }
    
        public virtual int usp_CMP_MEDICODelete(Nullable<int> cmedico_id)
        {
            var cmedico_idParameter = cmedico_id.HasValue ?
                new ObjectParameter("cmedico_id", cmedico_id) :
                new ObjectParameter("cmedico_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CMP_MEDICODelete", cmedico_idParameter);
        }
    
        public virtual int usp_CMP_MEDICOESPDelete(Nullable<int> cMEDICOESP_ID)
        {
            var cMEDICOESP_IDParameter = cMEDICOESP_ID.HasValue ?
                new ObjectParameter("CMEDICOESP_ID", cMEDICOESP_ID) :
                new ObjectParameter("CMEDICOESP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CMP_MEDICOESPDelete", cMEDICOESP_IDParameter);
        }
    
        public virtual int usp_CMP_MEDICOESPInsert(string vMEDICOESP_COD, Nullable<int> cMEDICO_ID, Nullable<int> nESPECIALIDAD_ID, Nullable<int> nINSTITUCIONEDU_ID, Nullable<int> nCREGIONAL_ID, Nullable<System.DateTime> dMEDICOESP_EMISION, Nullable<System.DateTime> dMEDICOESP_CADUCIDAD, Nullable<System.DateTime> dMEDICOESP_RESOLUCION)
        {
            var vMEDICOESP_CODParameter = vMEDICOESP_COD != null ?
                new ObjectParameter("VMEDICOESP_COD", vMEDICOESP_COD) :
                new ObjectParameter("VMEDICOESP_COD", typeof(string));
    
            var cMEDICO_IDParameter = cMEDICO_ID.HasValue ?
                new ObjectParameter("CMEDICO_ID", cMEDICO_ID) :
                new ObjectParameter("CMEDICO_ID", typeof(int));
    
            var nESPECIALIDAD_IDParameter = nESPECIALIDAD_ID.HasValue ?
                new ObjectParameter("NESPECIALIDAD_ID", nESPECIALIDAD_ID) :
                new ObjectParameter("NESPECIALIDAD_ID", typeof(int));
    
            var nINSTITUCIONEDU_IDParameter = nINSTITUCIONEDU_ID.HasValue ?
                new ObjectParameter("NINSTITUCIONEDU_ID", nINSTITUCIONEDU_ID) :
                new ObjectParameter("NINSTITUCIONEDU_ID", typeof(int));
    
            var nCREGIONAL_IDParameter = nCREGIONAL_ID.HasValue ?
                new ObjectParameter("NCREGIONAL_ID", nCREGIONAL_ID) :
                new ObjectParameter("NCREGIONAL_ID", typeof(int));
    
            var dMEDICOESP_EMISIONParameter = dMEDICOESP_EMISION.HasValue ?
                new ObjectParameter("DMEDICOESP_EMISION", dMEDICOESP_EMISION) :
                new ObjectParameter("DMEDICOESP_EMISION", typeof(System.DateTime));
    
            var dMEDICOESP_CADUCIDADParameter = dMEDICOESP_CADUCIDAD.HasValue ?
                new ObjectParameter("DMEDICOESP_CADUCIDAD", dMEDICOESP_CADUCIDAD) :
                new ObjectParameter("DMEDICOESP_CADUCIDAD", typeof(System.DateTime));
    
            var dMEDICOESP_RESOLUCIONParameter = dMEDICOESP_RESOLUCION.HasValue ?
                new ObjectParameter("DMEDICOESP_RESOLUCION", dMEDICOESP_RESOLUCION) :
                new ObjectParameter("DMEDICOESP_RESOLUCION", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CMP_MEDICOESPInsert", vMEDICOESP_CODParameter, cMEDICO_IDParameter, nESPECIALIDAD_IDParameter, nINSTITUCIONEDU_IDParameter, nCREGIONAL_IDParameter, dMEDICOESP_EMISIONParameter, dMEDICOESP_CADUCIDADParameter, dMEDICOESP_RESOLUCIONParameter);
        }
    
        public virtual int usp_CMP_MEDICOESPSelect(Nullable<int> cMEDICOESP_ID)
        {
            var cMEDICOESP_IDParameter = cMEDICOESP_ID.HasValue ?
                new ObjectParameter("CMEDICOESP_ID", cMEDICOESP_ID) :
                new ObjectParameter("CMEDICOESP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CMP_MEDICOESPSelect", cMEDICOESP_IDParameter);
        }
    
        public virtual int usp_CMP_MEDICOESPUpdate(Nullable<int> cMEDICOESP_ID, string vMEDICOESP_COD, Nullable<int> cMEDICO_ID, Nullable<int> nESPECIALIDAD_ID, Nullable<int> nINSTITUCIONEDU_ID, Nullable<int> nCREGIONAL_ID, Nullable<System.DateTime> dMEDICOESP_EMISION, Nullable<System.DateTime> dMEDICOESP_CADUCIDAD, Nullable<System.DateTime> dMEDICOESP_RESOLUCION)
        {
            var cMEDICOESP_IDParameter = cMEDICOESP_ID.HasValue ?
                new ObjectParameter("CMEDICOESP_ID", cMEDICOESP_ID) :
                new ObjectParameter("CMEDICOESP_ID", typeof(int));
    
            var vMEDICOESP_CODParameter = vMEDICOESP_COD != null ?
                new ObjectParameter("VMEDICOESP_COD", vMEDICOESP_COD) :
                new ObjectParameter("VMEDICOESP_COD", typeof(string));
    
            var cMEDICO_IDParameter = cMEDICO_ID.HasValue ?
                new ObjectParameter("CMEDICO_ID", cMEDICO_ID) :
                new ObjectParameter("CMEDICO_ID", typeof(int));
    
            var nESPECIALIDAD_IDParameter = nESPECIALIDAD_ID.HasValue ?
                new ObjectParameter("NESPECIALIDAD_ID", nESPECIALIDAD_ID) :
                new ObjectParameter("NESPECIALIDAD_ID", typeof(int));
    
            var nINSTITUCIONEDU_IDParameter = nINSTITUCIONEDU_ID.HasValue ?
                new ObjectParameter("NINSTITUCIONEDU_ID", nINSTITUCIONEDU_ID) :
                new ObjectParameter("NINSTITUCIONEDU_ID", typeof(int));
    
            var nCREGIONAL_IDParameter = nCREGIONAL_ID.HasValue ?
                new ObjectParameter("NCREGIONAL_ID", nCREGIONAL_ID) :
                new ObjectParameter("NCREGIONAL_ID", typeof(int));
    
            var dMEDICOESP_EMISIONParameter = dMEDICOESP_EMISION.HasValue ?
                new ObjectParameter("DMEDICOESP_EMISION", dMEDICOESP_EMISION) :
                new ObjectParameter("DMEDICOESP_EMISION", typeof(System.DateTime));
    
            var dMEDICOESP_CADUCIDADParameter = dMEDICOESP_CADUCIDAD.HasValue ?
                new ObjectParameter("DMEDICOESP_CADUCIDAD", dMEDICOESP_CADUCIDAD) :
                new ObjectParameter("DMEDICOESP_CADUCIDAD", typeof(System.DateTime));
    
            var dMEDICOESP_RESOLUCIONParameter = dMEDICOESP_RESOLUCION.HasValue ?
                new ObjectParameter("DMEDICOESP_RESOLUCION", dMEDICOESP_RESOLUCION) :
                new ObjectParameter("DMEDICOESP_RESOLUCION", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CMP_MEDICOESPUpdate", cMEDICOESP_IDParameter, vMEDICOESP_CODParameter, cMEDICO_IDParameter, nESPECIALIDAD_IDParameter, nINSTITUCIONEDU_IDParameter, nCREGIONAL_IDParameter, dMEDICOESP_EMISIONParameter, dMEDICOESP_CADUCIDADParameter, dMEDICOESP_RESOLUCIONParameter);
        }
    
        public virtual ObjectResult<usp_CMP_MEDICOInsert_Result> usp_CMP_MEDICOInsert(string cmedico_nrodoc, string cmedico_ncolegiatura, string vmedico_a_paterno, string vmedico_a_materno, string vmedico_nombres, string cmedico_estado, string vmedico_titulo, string vmedico_titulo_nro, string vmedico_correo, string vmedico_telefono, string vmedico_direccion, Nullable<int> ncregional_id, string cmedico_sexo, string cmedico_tipodoc, string vmedico_celular, Nullable<System.DateTime> dmedico_colegiatura, Nullable<int> ninstitucionedu_id, Nullable<System.DateTime> dmedico_nacimiento, string cmedico_recertificado, string cubigeo_cod)
        {
            var cmedico_nrodocParameter = cmedico_nrodoc != null ?
                new ObjectParameter("cmedico_nrodoc", cmedico_nrodoc) :
                new ObjectParameter("cmedico_nrodoc", typeof(string));
    
            var cmedico_ncolegiaturaParameter = cmedico_ncolegiatura != null ?
                new ObjectParameter("cmedico_ncolegiatura", cmedico_ncolegiatura) :
                new ObjectParameter("cmedico_ncolegiatura", typeof(string));
    
            var vmedico_a_paternoParameter = vmedico_a_paterno != null ?
                new ObjectParameter("vmedico_a_paterno", vmedico_a_paterno) :
                new ObjectParameter("vmedico_a_paterno", typeof(string));
    
            var vmedico_a_maternoParameter = vmedico_a_materno != null ?
                new ObjectParameter("vmedico_a_materno", vmedico_a_materno) :
                new ObjectParameter("vmedico_a_materno", typeof(string));
    
            var vmedico_nombresParameter = vmedico_nombres != null ?
                new ObjectParameter("vmedico_nombres", vmedico_nombres) :
                new ObjectParameter("vmedico_nombres", typeof(string));
    
            var cmedico_estadoParameter = cmedico_estado != null ?
                new ObjectParameter("cmedico_estado", cmedico_estado) :
                new ObjectParameter("cmedico_estado", typeof(string));
    
            var vmedico_tituloParameter = vmedico_titulo != null ?
                new ObjectParameter("vmedico_titulo", vmedico_titulo) :
                new ObjectParameter("vmedico_titulo", typeof(string));
    
            var vmedico_titulo_nroParameter = vmedico_titulo_nro != null ?
                new ObjectParameter("vmedico_titulo_nro", vmedico_titulo_nro) :
                new ObjectParameter("vmedico_titulo_nro", typeof(string));
    
            var vmedico_correoParameter = vmedico_correo != null ?
                new ObjectParameter("vmedico_correo", vmedico_correo) :
                new ObjectParameter("vmedico_correo", typeof(string));
    
            var vmedico_telefonoParameter = vmedico_telefono != null ?
                new ObjectParameter("vmedico_telefono", vmedico_telefono) :
                new ObjectParameter("vmedico_telefono", typeof(string));
    
            var vmedico_direccionParameter = vmedico_direccion != null ?
                new ObjectParameter("vmedico_direccion", vmedico_direccion) :
                new ObjectParameter("vmedico_direccion", typeof(string));
    
            var ncregional_idParameter = ncregional_id.HasValue ?
                new ObjectParameter("ncregional_id", ncregional_id) :
                new ObjectParameter("ncregional_id", typeof(int));
    
            var cmedico_sexoParameter = cmedico_sexo != null ?
                new ObjectParameter("cmedico_sexo", cmedico_sexo) :
                new ObjectParameter("cmedico_sexo", typeof(string));
    
            var cmedico_tipodocParameter = cmedico_tipodoc != null ?
                new ObjectParameter("cmedico_tipodoc", cmedico_tipodoc) :
                new ObjectParameter("cmedico_tipodoc", typeof(string));
    
            var vmedico_celularParameter = vmedico_celular != null ?
                new ObjectParameter("vmedico_celular", vmedico_celular) :
                new ObjectParameter("vmedico_celular", typeof(string));
    
            var dmedico_colegiaturaParameter = dmedico_colegiatura.HasValue ?
                new ObjectParameter("dmedico_colegiatura", dmedico_colegiatura) :
                new ObjectParameter("dmedico_colegiatura", typeof(System.DateTime));
    
            var ninstitucionedu_idParameter = ninstitucionedu_id.HasValue ?
                new ObjectParameter("ninstitucionedu_id", ninstitucionedu_id) :
                new ObjectParameter("ninstitucionedu_id", typeof(int));
    
            var dmedico_nacimientoParameter = dmedico_nacimiento.HasValue ?
                new ObjectParameter("dmedico_nacimiento", dmedico_nacimiento) :
                new ObjectParameter("dmedico_nacimiento", typeof(System.DateTime));
    
            var cmedico_recertificadoParameter = cmedico_recertificado != null ?
                new ObjectParameter("cmedico_recertificado", cmedico_recertificado) :
                new ObjectParameter("cmedico_recertificado", typeof(string));
    
            var cubigeo_codParameter = cubigeo_cod != null ?
                new ObjectParameter("cubigeo_cod", cubigeo_cod) :
                new ObjectParameter("cubigeo_cod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_MEDICOInsert_Result>("usp_CMP_MEDICOInsert", cmedico_nrodocParameter, cmedico_ncolegiaturaParameter, vmedico_a_paternoParameter, vmedico_a_maternoParameter, vmedico_nombresParameter, cmedico_estadoParameter, vmedico_tituloParameter, vmedico_titulo_nroParameter, vmedico_correoParameter, vmedico_telefonoParameter, vmedico_direccionParameter, ncregional_idParameter, cmedico_sexoParameter, cmedico_tipodocParameter, vmedico_celularParameter, dmedico_colegiaturaParameter, ninstitucionedu_idParameter, dmedico_nacimientoParameter, cmedico_recertificadoParameter, cubigeo_codParameter);
        }
    
        public virtual ObjectResult<usp_CMP_MEDICOSelect_Result> usp_CMP_MEDICOSelect(Nullable<int> cmedico_id)
        {
            var cmedico_idParameter = cmedico_id.HasValue ?
                new ObjectParameter("cmedico_id", cmedico_id) :
                new ObjectParameter("cmedico_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_MEDICOSelect_Result>("usp_CMP_MEDICOSelect", cmedico_idParameter);
        }
    
        public virtual ObjectResult<usp_CMP_MEDICOUpdate_Result> usp_CMP_MEDICOUpdate(Nullable<int> cmedico_id, string cmedico_nrodoc, string cmedico_ncolegiatura, string vmedico_a_paterno, string vmedico_a_materno, string vmedico_nombres, string cmedico_estado, string vmedico_titulo, string vmedico_titulo_nro, string vmedico_correo, string vmedico_telefono, string vmedico_direccion, Nullable<int> ncregional_id, string cmedico_sexo, string cmedico_tipodoc, string vmedico_celular, Nullable<System.DateTime> dmedico_colegiatura, Nullable<int> ninstitucionedu_id, Nullable<System.DateTime> dmedico_nacimiento, string cmedico_recertificado, string cubigeo_cod)
        {
            var cmedico_idParameter = cmedico_id.HasValue ?
                new ObjectParameter("cmedico_id", cmedico_id) :
                new ObjectParameter("cmedico_id", typeof(int));
    
            var cmedico_nrodocParameter = cmedico_nrodoc != null ?
                new ObjectParameter("cmedico_nrodoc", cmedico_nrodoc) :
                new ObjectParameter("cmedico_nrodoc", typeof(string));
    
            var cmedico_ncolegiaturaParameter = cmedico_ncolegiatura != null ?
                new ObjectParameter("cmedico_ncolegiatura", cmedico_ncolegiatura) :
                new ObjectParameter("cmedico_ncolegiatura", typeof(string));
    
            var vmedico_a_paternoParameter = vmedico_a_paterno != null ?
                new ObjectParameter("vmedico_a_paterno", vmedico_a_paterno) :
                new ObjectParameter("vmedico_a_paterno", typeof(string));
    
            var vmedico_a_maternoParameter = vmedico_a_materno != null ?
                new ObjectParameter("vmedico_a_materno", vmedico_a_materno) :
                new ObjectParameter("vmedico_a_materno", typeof(string));
    
            var vmedico_nombresParameter = vmedico_nombres != null ?
                new ObjectParameter("vmedico_nombres", vmedico_nombres) :
                new ObjectParameter("vmedico_nombres", typeof(string));
    
            var cmedico_estadoParameter = cmedico_estado != null ?
                new ObjectParameter("cmedico_estado", cmedico_estado) :
                new ObjectParameter("cmedico_estado", typeof(string));
    
            var vmedico_tituloParameter = vmedico_titulo != null ?
                new ObjectParameter("vmedico_titulo", vmedico_titulo) :
                new ObjectParameter("vmedico_titulo", typeof(string));
    
            var vmedico_titulo_nroParameter = vmedico_titulo_nro != null ?
                new ObjectParameter("vmedico_titulo_nro", vmedico_titulo_nro) :
                new ObjectParameter("vmedico_titulo_nro", typeof(string));
    
            var vmedico_correoParameter = vmedico_correo != null ?
                new ObjectParameter("vmedico_correo", vmedico_correo) :
                new ObjectParameter("vmedico_correo", typeof(string));
    
            var vmedico_telefonoParameter = vmedico_telefono != null ?
                new ObjectParameter("vmedico_telefono", vmedico_telefono) :
                new ObjectParameter("vmedico_telefono", typeof(string));
    
            var vmedico_direccionParameter = vmedico_direccion != null ?
                new ObjectParameter("vmedico_direccion", vmedico_direccion) :
                new ObjectParameter("vmedico_direccion", typeof(string));
    
            var ncregional_idParameter = ncregional_id.HasValue ?
                new ObjectParameter("ncregional_id", ncregional_id) :
                new ObjectParameter("ncregional_id", typeof(int));
    
            var cmedico_sexoParameter = cmedico_sexo != null ?
                new ObjectParameter("cmedico_sexo", cmedico_sexo) :
                new ObjectParameter("cmedico_sexo", typeof(string));
    
            var cmedico_tipodocParameter = cmedico_tipodoc != null ?
                new ObjectParameter("cmedico_tipodoc", cmedico_tipodoc) :
                new ObjectParameter("cmedico_tipodoc", typeof(string));
    
            var vmedico_celularParameter = vmedico_celular != null ?
                new ObjectParameter("vmedico_celular", vmedico_celular) :
                new ObjectParameter("vmedico_celular", typeof(string));
    
            var dmedico_colegiaturaParameter = dmedico_colegiatura.HasValue ?
                new ObjectParameter("dmedico_colegiatura", dmedico_colegiatura) :
                new ObjectParameter("dmedico_colegiatura", typeof(System.DateTime));
    
            var ninstitucionedu_idParameter = ninstitucionedu_id.HasValue ?
                new ObjectParameter("ninstitucionedu_id", ninstitucionedu_id) :
                new ObjectParameter("ninstitucionedu_id", typeof(int));
    
            var dmedico_nacimientoParameter = dmedico_nacimiento.HasValue ?
                new ObjectParameter("dmedico_nacimiento", dmedico_nacimiento) :
                new ObjectParameter("dmedico_nacimiento", typeof(System.DateTime));
    
            var cmedico_recertificadoParameter = cmedico_recertificado != null ?
                new ObjectParameter("cmedico_recertificado", cmedico_recertificado) :
                new ObjectParameter("cmedico_recertificado", typeof(string));
    
            var cubigeo_codParameter = cubigeo_cod != null ?
                new ObjectParameter("cubigeo_cod", cubigeo_cod) :
                new ObjectParameter("cubigeo_cod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_MEDICOUpdate_Result>("usp_CMP_MEDICOUpdate", cmedico_idParameter, cmedico_nrodocParameter, cmedico_ncolegiaturaParameter, vmedico_a_paternoParameter, vmedico_a_maternoParameter, vmedico_nombresParameter, cmedico_estadoParameter, vmedico_tituloParameter, vmedico_titulo_nroParameter, vmedico_correoParameter, vmedico_telefonoParameter, vmedico_direccionParameter, ncregional_idParameter, cmedico_sexoParameter, cmedico_tipodocParameter, vmedico_celularParameter, dmedico_colegiaturaParameter, ninstitucionedu_idParameter, dmedico_nacimientoParameter, cmedico_recertificadoParameter, cubigeo_codParameter);
        }
    
        public virtual int usp_CMP_PRESTADORADelete(Nullable<int> nprestadora_id)
        {
            var nprestadora_idParameter = nprestadora_id.HasValue ?
                new ObjectParameter("nprestadora_id", nprestadora_id) :
                new ObjectParameter("nprestadora_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CMP_PRESTADORADelete", nprestadora_idParameter);
        }
    
        public virtual ObjectResult<usp_CMP_PRESTADORAInsert_Result> usp_CMP_PRESTADORAInsert(string vprestadora_nom)
        {
            var vprestadora_nomParameter = vprestadora_nom != null ?
                new ObjectParameter("vprestadora_nom", vprestadora_nom) :
                new ObjectParameter("vprestadora_nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_PRESTADORAInsert_Result>("usp_CMP_PRESTADORAInsert", vprestadora_nomParameter);
        }
    
        public virtual ObjectResult<usp_CMP_PRESTADORASelect_Result> usp_CMP_PRESTADORASelect(Nullable<int> nprestadora_id)
        {
            var nprestadora_idParameter = nprestadora_id.HasValue ?
                new ObjectParameter("nprestadora_id", nprestadora_id) :
                new ObjectParameter("nprestadora_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_PRESTADORASelect_Result>("usp_CMP_PRESTADORASelect", nprestadora_idParameter);
        }
    
        public virtual ObjectResult<usp_CMP_PRESTADORAUpdate_Result> usp_CMP_PRESTADORAUpdate(Nullable<int> nprestadora_id, string vprestadora_nom)
        {
            var nprestadora_idParameter = nprestadora_id.HasValue ?
                new ObjectParameter("nprestadora_id", nprestadora_id) :
                new ObjectParameter("nprestadora_id", typeof(int));
    
            var vprestadora_nomParameter = vprestadora_nom != null ?
                new ObjectParameter("vprestadora_nom", vprestadora_nom) :
                new ObjectParameter("vprestadora_nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_PRESTADORAUpdate_Result>("usp_CMP_PRESTADORAUpdate", nprestadora_idParameter, vprestadora_nomParameter);
        }
    
        public virtual int usp_CMP_UBIGEODelete(string cUBIGEO_COD)
        {
            var cUBIGEO_CODParameter = cUBIGEO_COD != null ?
                new ObjectParameter("CUBIGEO_COD", cUBIGEO_COD) :
                new ObjectParameter("CUBIGEO_COD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CMP_UBIGEODelete", cUBIGEO_CODParameter);
        }
    
        public virtual ObjectResult<usp_CMP_UBIGEOInsert_Result> usp_CMP_UBIGEOInsert(string cUBIGEO_COD, string vUBIGEO_DEPARTAMENTO, string vUBIGEO_PROVINCIA, string vUBIGEO_DISTRITO)
        {
            var cUBIGEO_CODParameter = cUBIGEO_COD != null ?
                new ObjectParameter("CUBIGEO_COD", cUBIGEO_COD) :
                new ObjectParameter("CUBIGEO_COD", typeof(string));
    
            var vUBIGEO_DEPARTAMENTOParameter = vUBIGEO_DEPARTAMENTO != null ?
                new ObjectParameter("VUBIGEO_DEPARTAMENTO", vUBIGEO_DEPARTAMENTO) :
                new ObjectParameter("VUBIGEO_DEPARTAMENTO", typeof(string));
    
            var vUBIGEO_PROVINCIAParameter = vUBIGEO_PROVINCIA != null ?
                new ObjectParameter("VUBIGEO_PROVINCIA", vUBIGEO_PROVINCIA) :
                new ObjectParameter("VUBIGEO_PROVINCIA", typeof(string));
    
            var vUBIGEO_DISTRITOParameter = vUBIGEO_DISTRITO != null ?
                new ObjectParameter("VUBIGEO_DISTRITO", vUBIGEO_DISTRITO) :
                new ObjectParameter("VUBIGEO_DISTRITO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_UBIGEOInsert_Result>("usp_CMP_UBIGEOInsert", cUBIGEO_CODParameter, vUBIGEO_DEPARTAMENTOParameter, vUBIGEO_PROVINCIAParameter, vUBIGEO_DISTRITOParameter);
        }
    
        public virtual ObjectResult<usp_CMP_UBIGEOSelect_Result> usp_CMP_UBIGEOSelect(string cUBIGEO_COD)
        {
            var cUBIGEO_CODParameter = cUBIGEO_COD != null ?
                new ObjectParameter("CUBIGEO_COD", cUBIGEO_COD) :
                new ObjectParameter("CUBIGEO_COD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_UBIGEOSelect_Result>("usp_CMP_UBIGEOSelect", cUBIGEO_CODParameter);
        }
    
        public virtual ObjectResult<usp_CMP_UBIGEOUpdate_Result> usp_CMP_UBIGEOUpdate(string cUBIGEO_COD, string vUBIGEO_DEPARTAMENTO, string vUBIGEO_PROVINCIA, string vUBIGEO_DISTRITO)
        {
            var cUBIGEO_CODParameter = cUBIGEO_COD != null ?
                new ObjectParameter("CUBIGEO_COD", cUBIGEO_COD) :
                new ObjectParameter("CUBIGEO_COD", typeof(string));
    
            var vUBIGEO_DEPARTAMENTOParameter = vUBIGEO_DEPARTAMENTO != null ?
                new ObjectParameter("VUBIGEO_DEPARTAMENTO", vUBIGEO_DEPARTAMENTO) :
                new ObjectParameter("VUBIGEO_DEPARTAMENTO", typeof(string));
    
            var vUBIGEO_PROVINCIAParameter = vUBIGEO_PROVINCIA != null ?
                new ObjectParameter("VUBIGEO_PROVINCIA", vUBIGEO_PROVINCIA) :
                new ObjectParameter("VUBIGEO_PROVINCIA", typeof(string));
    
            var vUBIGEO_DISTRITOParameter = vUBIGEO_DISTRITO != null ?
                new ObjectParameter("VUBIGEO_DISTRITO", vUBIGEO_DISTRITO) :
                new ObjectParameter("VUBIGEO_DISTRITO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CMP_UBIGEOUpdate_Result>("usp_CMP_UBIGEOUpdate", cUBIGEO_CODParameter, vUBIGEO_DEPARTAMENTOParameter, vUBIGEO_PROVINCIAParameter, vUBIGEO_DISTRITOParameter);
        }
    
        public virtual ObjectResult<usp_Medicos_by_CRegionalID_Result> usp_Medicos_by_CRegionalID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Medicos_by_CRegionalID_Result>("usp_Medicos_by_CRegionalID", idParameter);
        }
    
        public virtual ObjectResult<usp_Pasantia_By_MedicoID_Result> usp_Pasantia_By_MedicoID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Pasantia_By_MedicoID_Result>("usp_Pasantia_By_MedicoID", idParameter);
        }
    
        public virtual ObjectResult<usp_Pasantia_By_PrestadoraID_Result> usp_Pasantia_By_PrestadoraID(Nullable<int> id, Nullable<System.DateTime> inicio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("inicio", inicio) :
                new ObjectParameter("inicio", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Pasantia_By_PrestadoraID_Result>("usp_Pasantia_By_PrestadoraID", idParameter, inicioParameter);
        }
    
        public virtual ObjectResult<usp_PostGrado_By_MedicoID_Result> usp_PostGrado_By_MedicoID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PostGrado_By_MedicoID_Result>("usp_PostGrado_By_MedicoID", idParameter);
        }
    
        public virtual ObjectResult<usp_List_Medicos_Result> usp_List_Medicos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_List_Medicos_Result>("usp_List_Medicos");
        }
    
        public virtual ObjectResult<usp_Medico_By_Id_Result> usp_Medico_By_Id(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Medico_By_Id_Result>("usp_Medico_By_Id", idParameter);
        }
    
        public virtual ObjectResult<usp_Especialidad_By_MedicoID_Result> usp_Especialidad_By_MedicoID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Especialidad_By_MedicoID_Result>("usp_Especialidad_By_MedicoID", idParameter);
        }
    
        public virtual ObjectResult<usp_Medico_By_NroCol_Result> usp_Medico_By_NroCol(string nro)
        {
            var nroParameter = nro != null ?
                new ObjectParameter("nro", nro) :
                new ObjectParameter("nro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Medico_By_NroCol_Result>("usp_Medico_By_NroCol", nroParameter);
        }
    
        public virtual ObjectResult<usp_List_CRegional_Result> usp_List_CRegional()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_List_CRegional_Result>("usp_List_CRegional");
        }
    
        public virtual ObjectResult<usp_Medico_By_Paterno_Result> usp_Medico_By_Paterno(string paterno)
        {
            var paternoParameter = paterno != null ?
                new ObjectParameter("paterno", paterno) :
                new ObjectParameter("paterno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Medico_By_Paterno_Result>("usp_Medico_By_Paterno", paternoParameter);
        }
    
        public virtual ObjectResult<usp_List_MedicosInstEdu_Result> usp_List_MedicosInstEdu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_List_MedicosInstEdu_Result>("usp_List_MedicosInstEdu");
        }
    }
}
